<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\RepositoryInterface\Categories\" />
    <Folder Include="Contracts\RepositoryInterface\Transactions\" />
    <Folder Include="Contracts\RepositoryInterface\Notifications\" />
    <Folder Include="Common\" />
    <Folder Include="Models\Budgets\Dtos\" />
    <Folder Include="Models\Budgets\Validators\" />
    <Folder Include="Models\Categories\" />
    <Folder Include="Models\Transactions\" />
    <Folder Include="Models\Notifications\" />
    <Folder Include="Models\Users\ResponseDto\" />
    <Folder Include="Models\Users\Validator\QueryValidator\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="11.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpenseTrackerDomainLayer\ExpenseTrackerDomainLayer.csproj" />
  </ItemGroup>

</Project>
